services:
  demo:
  tms:
  wmts:
  wms:
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']

layers:
  - name: glri_projects
    title: GLRI Projects
    sources: [glri_projects_cache]

  - name: osm_bright
    title: OpenStreetMap Bright Layer
    sources: [osm_bright_cache]

  - name: transparent_stutt
    title: Transparent Stuttgart Layer
    sources: [transparent_stutt_cache]  # Use the new cache

caches:
  glri_projects_cache:
    grids: [osm_bright_grid]
    sources: [glri_projects_source]

  osm_bright_cache:
    grids: [osm_bright_grid]
    sources: [osm_bright_source]
    format: image/png

  transparent_stutt_cache:
    grids: [osm_bright_grid]  # Use the same grid as other caches
    sources: [transparent_stutt_source]
    format: image/png  # Adjust format if necessary

sources:
  glri_projects_source:
    type: wms
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']
    req:
      url: http://crystalball.timetochange.today/geoserver/workspace1/ows
      layers: glri_projects
      transparent: true

  osm_bright_source:
    type: tile
    url: https://geo.timetochange.today/geoserver/gwc/service/tms/1.0.0/osm:osm_bright@EPSG:900913@png/%(z)s/%(x)s/%(y)s.png
    grid: osm_bright_grid_reverse

  transparent_stutt_source:
    type: mbtiles
    filename: /mapproxy/data/transparent_stutt.mbtiles  # Path to the MBTiles file inside the container

grids:
  osm_bright_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw

  osm_bright_grid_reverse:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: sw

globals:
  cache:
    base_dir: '/mapproxy/cache_data'
    lock_dir: '/mapproxy/cache_data/locks'

  image:
    resampling_method: bilinear
    jpeg_quality: 90
