

services:

 #sets up how to make the source data available

 demo:

 tms:

 wmts:

 wms:

   #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.

   srs: ['EPSG:4326', 'EPSG:3857']

   image_formats: ['image/jpeg', 'image/png']


layers:

 #sets up which layers you want to make available using the services above.

 - name: luftbild_aktuell

   title: luftbild aktuell

   sources: [luftbild_aktuell_cache] # This layer should use the glri_projects_cache (defined below) as its source.


 - name: osm_bright

   title: OpenStreetMap Bright Layer

   sources: [osm_bright_cache] # This layer uses the osm_bright_cache defined below.


caches:

   #sets up how to cache the source data

 luftbild_aktuell_cache:

   grids: [osm_bright_grid]

   sources: [luftbild_aktuell_source] # Here you set what source data (defined below) you want to cache


 osm_bright_cache:

   grids: [osm_bright_grid]

   sources: [osm_bright_source] # Here you set what source data (defined below) you want to cache

   format: image/png



sources:

  luftbild_aktuell_source:

     type: wms

     supported_formats: [png]

     supported_srs: ['EPSG:3857', 'CRS:84']

     req:

       url: https://geoserver.stuttgart.de/geoserver/workspace1/wms

       layers: A62_Luftbild_2023_EPSG25832

       transparent: true


  osm_bright_source:

     type: tile

     url: https://geo.timetochange.today/geoserver/gwc/service/tms/1.0.0/osm:osm_bright@EPSG:900913@png/%(z)s/%(x)s/%(y)s.png

     grid: osm_bright_grid_reverse
     

grids:

 osm_bright_grid:

   base: GLOBAL_MERCATOR

   srs: 'EPSG:3857'

   origin: nw


 osm_bright_grid_reverse:

   base: GLOBAL_MERCATOR

   srs: 'EPSG:3857'

   origin: sw


globals:

 #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.

 cache:

   # where to store the cached images

   base_dir: './cache_data'

   # where to store lockfiles

   lock_dir: './cache_data/locks'


 # image/transformation options

 image:

     resampling_method: bilinear

     jpeg_quality: 90
